# Generated by Django 4.2.1 on 2025-02-06 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='ЗАголовок')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Заголовк')),
                ('disc', models.CharField(max_length=64, verbose_name='Описание')),
                ('email', models.EmailField(max_length=32, verbose_name='Email')),
                ('img', models.ImageField(default='images/default.png', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='Фото')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, related_name='ads', to='ads.category')),
            ],
        ),
    ]
