# Generated by Django 4.2.1 on 2025-02-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='img',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
