# Generated by Django 4.2.1 on 2025-02-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_category_ad_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Адрес электронной почты автора'),
        ),
    ]
