# Generated by Django 4.2.1 on 2025-02-04 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Заголовок')),
                ('discription', models.CharField(max_length=64, verbose_name='Описание')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('image', models.ImageField(default='images/default.png', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='Фотка')),
                ('date_of_published', models.DateField(auto_now_add=True, verbose_name='Дата публицации')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('categories', models.ManyToManyField(blank=True, related_name='ads', to='ads.category')),
            ],
        ),
    ]
