# Generated by Django 4.2.1 on 2025-02-05 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Заголовок')),
                ('disc', models.CharField(max_length=64, verbose_name='Описание')),
                ('email', models.EmailField(max_length=32, verbose_name='Email')),
                ('image', models.ImageField(blank=True, default='images/default.png', upload_to='image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='Image')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(blank=True, related_name='ads', to='ads.category')),
            ],
        ),
    ]
